### ISSUE TITLE
Installation error TS CRA template

### ISSUE THREAD

**Issue by Gercov** [feature-sliced/cra-template#11]
Npx throw 404 status error
`'cra-template-feature-sliced-typescript@latest' is not in the npm registry.`

**Comment by azinit** [comment]
Hello!
Unfortunately, for typescript is not yet ready 🤔 

Thanks for your feedback, I've actualized README
![image](https://user-images.githubusercontent.com/42924400/153869589-29515ada-f599-4b4d-8e4f-a7120307a32a.png)

https://www.npmjs.com/package/@feature-sliced/cra-template
